import type { Booking } from "@/features/bookings/bookings.types"

export const mockBookings: Booking[] = [
  {
    id: "bk_1001",
    code: "ALP-BK-1001",
    customerName: "Nadia Prameswari",
    activityTitle: "Mount Batur Sunrise Trekking",
    destination: "Bali, Indonesia",
    agentName: "Bali Horizon Trips",
    status: "paid_upcoming",
    paymentStatus: "paid",
    bookingDate: "2026-07-01",
    travelDate: "2026-07-14",
    totalAmount: 1850000,
    currency: "IDR",
    internalNote: "Customer requested pickup confirmation one day before travel.",
  },
  {
    id: "bk_1002",
    code: "ALP-BK-1002",
    customerName: "Rafi Mahendra",
    activityTitle: "Komodo Island Boat Day Tour",
    destination: "Labuan Bajo, Indonesia",
    agentName: "Flores Blue Water",
    status: "pending_payment",
    paymentStatus: "pending",
    bookingDate: "2026-07-02",
    travelDate: "2026-07-19",
    totalAmount: 3200000,
    currency: "IDR",
    internalNote: "Payment reminder should be sent before expiry.",
  },
  {
    id: "bk_1003",
    code: "ALP-BK-1003",
    customerName: "Sarah Lim",
    activityTitle: "Private Heritage Food Walk",
    destination: "Singapore",
    agentName: "City Plate Collective",
    status: "ongoing",
    paymentStatus: "paid",
    bookingDate: "2026-06-28",
    travelDate: "2026-07-07",
    totalAmount: 210,
    currency: "USD",
    internalNote: "VIP guest, agent should confirm guide language preference.",
  },
  {
    id: "bk_1004",
    code: "ALP-BK-1004",
    customerName: "Kevin Tan",
    activityTitle: "Kyoto Night Photography Route",
    destination: "Kyoto, Japan",
    agentName: "Frame Japan",
    status: "finished",
    paymentStatus: "paid",
    bookingDate: "2026-06-10",
    travelDate: "2026-06-25",
    totalAmount: 175,
    currency: "USD",
  },
  {
    id: "bk_1005",
    code: "ALP-BK-1005",
    customerName: "Maya Putri",
    activityTitle: "Raja Ampat Snorkeling Camp",
    destination: "West Papua, Indonesia",
    agentName: "Aqua North Expeditions",
    status: "cancelled",
    paymentStatus: "refunded",
    bookingDate: "2026-06-22",
    travelDate: "2026-07-30",
    totalAmount: 7800000,
    currency: "IDR",
  },
  {
    id: "bk_1006",
    code: "ALP-BK-1006",
    customerName: "Alicia Morgan",
    activityTitle: "Bangkok Canal Market Tour",
    destination: "Bangkok, Thailand",
    agentName: "Siam Local Paths",
    status: "expired",
    paymentStatus: "failed",
    bookingDate: "2026-06-30",
    travelDate: "2026-07-05",
    totalAmount: 92,
    currency: "USD",
  },
  {
    id: "bk_1007",
    code: "ALP-BK-1007",
    customerName: "Dimas Wardana",
    activityTitle: "Lombok Surf Coaching",
    destination: "Lombok, Indonesia",
    agentName: "South Coast Surf",
    status: "paid_upcoming",
    paymentStatus: "paid",
    bookingDate: "2026-07-03",
    travelDate: "2026-07-22",
    totalAmount: 1250000,
    currency: "IDR",
  },
  {
    id: "bk_1008",
    code: "ALP-BK-1008",
    customerName: "Citra Amelia",
    activityTitle: "Ubud Ceramic Studio Session",
    destination: "Bali, Indonesia",
    agentName: "Clay Village Studio",
    status: "pending_payment",
    paymentStatus: "pending",
    bookingDate: "2026-07-04",
    travelDate: "2026-07-16",
    totalAmount: 680000,
    currency: "IDR",
  },
  {
    id: "bk_1009",
    code: "ALP-BK-1009",
    customerName: "Tobias Richter",
    activityTitle: "Saigon Street Coffee Trail",
    destination: "Ho Chi Minh City, Vietnam",
    agentName: "District Brew Tours",
    status: "finished",
    paymentStatus: "paid",
    bookingDate: "2026-06-05",
    travelDate: "2026-06-18",
    totalAmount: 48,
    currency: "USD",
  },
  {
    id: "bk_1010",
    code: "ALP-BK-1010",
    customerName: "Intan Larasati",
    activityTitle: "Yogyakarta Temple Cycling",
    destination: "Yogyakarta, Indonesia",
    agentName: "Jogja Pedal Works",
    status: "ongoing",
    paymentStatus: "paid",
    bookingDate: "2026-07-01",
    travelDate: "2026-07-07",
    totalAmount: 940000,
    currency: "IDR",
  },
  {
    id: "bk_1011",
    code: "ALP-BK-1011",
    customerName: "Oscar Wijaya",
    activityTitle: "Penang Mural and Food Route",
    destination: "Penang, Malaysia",
    agentName: "George Town Stories",
    status: "paid_upcoming",
    paymentStatus: "paid",
    bookingDate: "2026-07-05",
    travelDate: "2026-08-02",
    totalAmount: 85,
    currency: "USD",
  },
  {
    id: "bk_1012",
    code: "ALP-BK-1012",
    customerName: "Grace Huang",
    activityTitle: "Chiang Mai Elephant Sanctuary Visit",
    destination: "Chiang Mai, Thailand",
    agentName: "Northern Care Travel",
    status: "pending_payment",
    paymentStatus: "failed",
    bookingDate: "2026-07-06",
    travelDate: "2026-07-26",
    totalAmount: 130,
    currency: "USD",
  },
]
